### ISSUE TITLE
Bonjour Error codes

### ISSUE THREAD

**Issue by STL1811** [arkane-systems/Arkane.Zeroconf#7]
Hi,
Some new error codes are added to Bonjour service :
you can add them to SerivceError.cs

        BadSig = -65560,
        BadKey = -65561,
        Transient = -65562,
        ServiceNotRunning = -65563,  /* Background daemon not running * /
        NatPortMappingUnsupported = -65564,  /* NAT doesn't support PCP, NAT-PMP or UPnP * / 
       NatPortMappingDisabled = -65565,  /* NAT supports PCP, NAT-PMP or UPnP, but it's disabled by the administrator * /
        NoRouter = -65566,  /* No router currently configured (probably no network connectivity) * /
        PollingMode = -65567,
        Timeout = -65568

**Comment by cerebrate** [comment]
Will be included in next release.
